// src/components/StatusBadge.tsx
import Badge from '@/components/ui/Badge';
import type { RequestStatus } from '@/types';
import { requestStatusLabels } from '@/lib/utils';

interface StatusBadgeProps {
  status: RequestStatus;
}

const statusVariants: Record<RequestStatus, 'default' | 'success' | 'warning' | 'error' | 'info'> = {
  pending: 'default',
  in_progress: 'info',
  review: 'warning',
  done: 'success',
  failed: 'error',
};

export default function StatusBadge({ status }: StatusBadgeProps) {
  return <Badge variant={statusVariants[status]}>{requestStatusLabels[status]}</Badge>;
}

// src/app/components/status-badge/status-badge.component.ts
import { Component, Input } from '@angular/core';
import { BadgeComponent } from '@app/components/ui/badge/badge.component';
import { RequestStatus } from '@app/types';
import { requestStatusLabels } from '@app/lib/utils';

@Component({
  selector: 'app-status-badge',
  standalone: true,
  imports: [BadgeComponent],
  template: `
    <app-badge [variant]="statusVariants[status]">{{ statusLabels[status] }}</app-badge>
  `,
})
export class StatusBadgeComponent {
  @Input({ required: true }) status!: RequestStatus;

  readonly statusLabels = requestStatusLabels;

  readonly statusVariants: Record<RequestStatus, 'default' | 'success' | 'warning' | 'error' | 'info'> = {
    pending: 'default',
    in_progress: 'info',
    review: 'warning',
    done: 'success',
    failed: 'error',
  };
}
