// src/app/components/shared/header.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import { LucideAngularModule, LogOut, User } from 'lucide-angular';
import { ButtonComponent } from '../ui/button.component';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [CommonModule, LucideAngularModule, ButtonComponent],
  template: `
    <header
      class="flex h-16 items-center justify-between border-b border-gray-200 bg-white px-6 dark:border-gray-700 dark:bg-gray-800"
    >
      <div>
        <h1 class="text-lg font-semibold text-gray-900 dark:text-gray-100">DevPortal</h1>
      </div>

      <div class="flex items-center gap-4">
        @if (authService.currentUser; as user) {
          <div class="flex items-center gap-2 text-sm text-gray-700 dark:text-gray-300">
            <lucide-icon [img]="UserIcon" [size]="16"></lucide-icon>
            <span>{{ user.name || user.email }}</span>
          </div>
        }

        <app-button variant="ghost" size="sm" (click)="onLogout()">
          <lucide-icon [img]="LogOutIcon" [size]="16" class="mr-2"></lucide-icon>
          Sair
        </app-button>
      </div>
    </header>
  `,
})
export class HeaderComponent {
  readonly UserIcon = User;
  readonly LogOutIcon = LogOut;

  constructor(
    readonly authService: AuthService,
    private readonly router: Router,
  ) {}

  onLogout(): void {
    this.authService.logout();
    this.router.navigate(['/login']);
  }
}

// src/components/Header.tsx
import { LogOut, User } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import Button from '@/components/ui/Button';
import { useAuth } from '@/contexts/AuthContext';

export default function Header() {
  const { user, logout } = useAuth();
  const navigate = useNavigate();

  const handleLogout = async () => {
    await logout();
    navigate('/login');
  };

  return (
    <header className="flex h-16 items-center justify-between border-b border-gray-200 bg-white px-6 dark:border-gray-700 dark:bg-gray-800">
      <div>
        <h1 className="text-lg font-semibold text-gray-900 dark:text-gray-100">DevPortal</h1>
      </div>

      <div className="flex items-center gap-4">
        {user && (
          <div className="flex items-center gap-2 text-sm text-gray-700 dark:text-gray-300">
            <User className="h-4 w-4" />
            <span>{user.name || user.email}</span>
          </div>
        )}

        <Button
          variant="ghost"
          size="sm"
          onClick={handleLogout}
        >
          <LogOut className="mr-2 h-4 w-4" />
          Sair
        </Button>
      </div>
    </header>
  );
}
